version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_net

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: uhtOFlQll29Y5Qja
      MYSQL_DATABASE: php_online_discussion_forum
      MYSQL_USER: online_discussion_usr
      MYSQL_PASSWORD: X0M8baWg6zxvAqPV
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"  # Change port if needed
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: uhtOFlQll29Y5Qja  # Change if different
    networks:
      - app_net

networks:
  app_net:

volumes:
  mysql_data:
